# 链上合约地址配置

navi_core = "0xNAVICORECONTRACTPLACEHOLDER"
navi_market = "0xNAVIMARKETPLACEHOLDER"
navi_price_oracle = "0xNAVIORACLEPLACEHOLDER"
deepbook_pool = "0xDEEPBOOKPOOLPLACEHOLDER"

[lending_navi]
rpc_endpoint = "https://fullnode.mainnet.sui.io:443"
package_id = "0x81c408448d0d57b3e371ea94de1d40bf852784d3e225de1e74acab3e8395c18f"
module = "incentive_v3"
function = "entry_deposit"
withdraw_function = "withdraw"
borrow_function = "borrow"
repay_function = "entry_repay"
coin_type = "0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC"
coin_decimals = 6
asset_id = "usdc"
borrow_coin_type = "0x356a26eb9e012a68958082340d4c4116e7f55615cf27affcff209cf0ae544f59::wal::WAL"
borrow_coin_decimals = 9
borrow_asset_id = "wal"
gas_budget = 60_000_000

[lending_navi.clock]
object_id = "0x0000000000000000000000000000000000000000000000000000000000000006"
initial_shared_version = 1
mutable = false

[lending_navi.oracle]
object_id = "0x1568865ed9a0b5ec414220e8f79b3d04c77acc82358f6e5ae4635687392ffbef"
initial_shared_version = 8_202_835
mutable = false

[lending_navi.storage]
object_id = "0xbb4e2f4b6205c2e2a2db47aeb4f830796ec7c005f88537ee775986639bc442fe"
initial_shared_version = 8_202_844
mutable = true

[lending_navi.collateral_pool]
object_id = "0xa3582097b4c57630046c0c49a88bfc6b202a3ec0a9db5597c31765f7563755a8"
initial_shared_version = 372_449_049
mutable = true

[lending_navi.borrow_pool]
object_id = "0xef76883525f5c2ff90cd97732940dbbdba0b391e29de839b10588cee8e4fe167"
initial_shared_version = 510_342_415
mutable = true

[lending_navi.incentive_v2]
object_id = "0xf87a8acb8b81d14307894d12595541a73f19933f88e1326d5be349c7a6f7559c"
initial_shared_version = 38_232_222
mutable = true

[lending_navi.incentive_v3]
object_id = "0x62982dad27fb10bb314b3384d5de8d2ac2d72ab2dbeae5d801dbdb9efa816c80"
initial_shared_version = 496_060_210
mutable = true

[deepbook_execution]
rpc_endpoint = "https://fullnode.mainnet.sui.io:443"
package_id = "0x0517b8c5ca29fbb9f09cf77530ba331f30f59b6203d13d28796e76e362cc0e12"
module = "deepbookv3_utils"
function = "place_limit_order"
base_type = "0x356a26eb9e012a68958082340d4c4116e7f55615cf27affcff209cf0ae544f59::wal::WAL"
quote_type = "0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC"
price_scale = 1_000_000
quantity_scale = 1_000_000_000
restriction = 0
self_matching_prevention = 0
post_only = true
client_order_id_start = 1
gas_budget = 50_000_000

[[deepbook_execution.shared_objects]]
object_id = "0xff1141ef80e7baf206c7930c274b465600e64884d8167f90d4cdb60197925163"
initial_shared_version = 341697211
mutable = true

[[deepbook_execution.shared_objects]]
object_id = "0x5c1a039f97ed1cbd84d54b5d633bdffd681086acc38961b1d366c4ecf680d150"
initial_shared_version = 341697211
mutable = true

[[deepbook_execution.shared_objects]]
object_id = "0x56a1c985c1f1123181d6b881714793689321ba24301b3585eec427436eb1c76d"
initial_shared_version = 414947427
mutable = true

[[deepbook_execution.shared_objects]]
object_id = "0xd721801d92d472e83d970de75865daf1698463021e6b24589585595549acd499"
initial_shared_version = 663134436
mutable = true

[deepbook_execution.clock]
object_id = "0x0000000000000000000000000000000000000000000000000000000000000006"
initial_shared_version = 1
mutable = false
